name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy .env file
      run: cp .env.template .env

    - name: Run tests
      run: |
        pytest
      env:
        MQTT_BROKER: localhost
        MQTT_PORT: 1883
        MQTT_USERNAME: user
        MQTT_PASSWORD: password
        FLASK_RUN_HOST: 0.0.0.0
        FLASK_RUN_PORT: 5000
        JWT_SECRET_KEY: your_jwt_secret_key
        JWT_ACCESS_TOKEN_EXPIRES: 3600
        MONGODB_URI: mongodb://localhost:27017
        MONGODB_DBNAME: db_name

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip source files
      run: zip -r iot-device-server.zip . --exclude .git\* --exclude .github\*

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
    
    - name: Upload to S3
      run: |
        aws s3 cp iot-device-server.zip s3://elasticbeanstalk-eu-north-1-272154733490/

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version --application-name 2 --version-label ${{ github.sha }} --source-bundle S3Bucket=elasticbeanstalk-eu-north-1-272154733490,S3Key=iot-device-server.zip
        aws elasticbeanstalk update-environment --application-name 2 --environment-name 2-env --version-label ${{ github.sha }}
